ARG BASE=alpine:3

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

ADD artifacts/regctl-${VERSION}-${TARGETOS}-${TARGETARCH} /usr/local/bin/regctl
ADD artifacts/regsync-${VERSION}-${TARGETOS}-${TARGETARCH} /usr/local/bin/regsync
ADD artifacts/regbot-${VERSION}-${TARGETOS}-${TARGETARCH} /usr/local/bin/regbot
