name: Close inactive issues
on:
  schedule:
    - cron: "15 5 * * 1"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 60
          days-before-close: 28
          only-labels: feedback-needed
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 60 days waiting for feedback. It will be automatically closed in 28 days."
          close-issue-message: "This issue was closed because it has been inactive for 28 days since being marked as stale."
          stale-pr-message: "This PR is stale because it has been open for 60 days waiting for feedback. It will be automatically closed in 28 days."
          close-pr-message: "This PR was closed because it has been inactive for 28 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}